cpan: Fix ba500568 regression, escape $ character
Regression was introduced by ba5005689bac0f5bcfc8a9531da3c576260ceef2
Without escaping $ character I'm getting the following error:

> Global symbol "$FLATPAK_DEST" requires explicit package name (did you forget to declare "my $FLATPAK_DEST"?) at /app/bin/flatpak-cpan-generator.pl line 125.
> Global symbol "$FLATPAK_DEST" requires explicit package name (did you forget to declare "my $FLATPAK_DEST"?) at /app/bin/flatpak-cpan-generator.pl line 125.
> Bareword "main" not allowed while "strict subs" in use at /app/bin/flatpak-cpan-generator.pl line 140.
> Execution of /app/bin/flatpak-cpan-generator.pl aborted due to compilation errors.